// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  bazaSidebar: [{type: 'autogenerated', dirName: 'baza'}],
  polnayaSidebar: [{type: 'autogenerated', dirName: 'polnaya'}],
  modulesSidebar: [{type: 'autogenerated', dirName: 'modules'}],
  resourcesSidebar: [
    {type: 'autogenerated', dirName: 'resources'},
    {
      type: 'category',
      label: 'Руководства',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
  ],
  legalSidebar: [{type: 'autogenerated', dirName: 'legal'}],
};

export default sidebars;
