// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  bazaSidebar: [{type: 'autogenerated', dirName: 'baza'}],
  polnayaSidebar: [{type: 'autogenerated', dirName: 'polnaya'}],
  modulesSidebar: [
    {
      type: 'category',
      label: 'Продвинутый трек (Claude)',
      items: [{type: 'autogenerated', dirName: 'modules'}],
    },
    {
      type: 'category',
      label: 'Руководства',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
  ],
  resourcesSidebar: [{type: 'autogenerated', dirName: 'resources'}],
  legalSidebar: [{type: 'autogenerated', dirName: 'legal'}],
};

export default sidebars;
