// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  modulesSidebar: [
    {
      type: 'category',
      label: 'Модули программы',
      link: {type: 'doc', id: 'modules/index'},
      items: [{type: 'autogenerated', dirName: 'modules'}],
    },
    {
      type: 'category',
      label: 'Руководства',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
  ],
  resourcesSidebar: [{type: 'autogenerated', dirName: 'resources'}],
};

export default sidebars;
